### ISSUE TITLE
single-letter names

### ISSUE THREAD

**Issue by stevenvachon** [Rebelmail/posthtml-uglify#20]
if possible.

```css
.a { prop: value }
```
is shorter than
```css
.xz { prop: value }
```
